#!/usr/bin/env ruby
#^syntax detection

forge "http://forge.puppetlabs.com"

mod "puppetlabs/apt", "1.4.2"
mod "puppetlabs/nodejs", "0.4.0"
mod "puppetlabs/apache", "1.0.1"
mod "puppetlabs/git", "0.0.3"
mod "puppetlabs/mysql", "2.2.3"
mod "example42/puppi", "2.1.9"
mod "example42/php", "2.0.18"
mod "tPl0ch/composer", "1.2.1"
